import { useState } from "react";

function AccountSettingsPage() {
  const [profile, setProfile] = useState({ name: "Retailer", email: "retailer@supplysync.demo", role: "Retailer" });
  const [notifications, setNotifications] = useState({ lowStock: true, orders: true, suppliers: false });
  const [preferences, setPreferences] = useState({ currency: "INR", refresh: "Every 15 minutes" });
  const [saved, setSaved] = useState(false);

  function updateProfile(event) { setProfile({ ...profile, [event.target.name]: event.target.value }); setSaved(false); }
  function toggleNotification(name) { setNotifications({ ...notifications, [name]: !notifications[name] }); setSaved(false); }

  return <div className="min-h-screen bg-slate-50 text-slate-900">
    <header className="border-b border-slate-200/80 bg-white shadow-sm"><div className="mx-auto flex min-h-24 max-w-5xl items-center justify-between px-4 sm:px-6 lg:px-8"><div><p className="text-sm font-medium text-slate-400">Retailer Portal</p><h2 className="mt-1 text-xl font-bold tracking-tight text-slate-900">Account Settings</h2></div><div className="flex h-10 w-10 items-center justify-center rounded-full bg-blue-100 font-semibold text-blue-700">R</div></div></header>
    <main className="mx-auto max-w-5xl px-4 py-8 sm:px-6 lg:px-8 lg:py-10"><div className="mb-8"><p className="mb-2 text-xs font-bold uppercase tracking-[0.16em] text-blue-600">Workspace preferences</p><h1 className="text-3xl font-bold tracking-tight text-slate-900">Account Settings</h1><p className="mt-2 text-sm text-slate-500">Manage your profile, notifications and SupplySync workspace preferences.</p></div>
      <div className="space-y-6">
        <SettingsSection title="Profile Information" description="These details are used to identify your retailer workspace."><div className="grid grid-cols-1 gap-5 sm:grid-cols-2"><Field label="Name"><input name="name" value={profile.name} onChange={updateProfile} className="h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 text-sm text-slate-900 outline-none transition focus:border-blue-500 focus:bg-white focus:ring-4 focus:ring-blue-50" /></Field><Field label="Email"><input name="email" type="email" value={profile.email} onChange={updateProfile} className="h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 text-sm text-slate-900 outline-none transition focus:border-blue-500 focus:bg-white focus:ring-4 focus:ring-blue-50" /></Field><Field label="Role"><input value={profile.role} readOnly className="h-11 w-full rounded-xl border border-slate-200 bg-slate-100 px-4 text-sm text-slate-500 outline-none" /></Field></div></SettingsSection>
        <SettingsSection title="Notification Preferences" description="Choose which operational updates you would like to receive."><div className="divide-y divide-slate-100">{[["lowStock", "Low Stock Alerts", "Get notified when products reach their reorder level."], ["orders", "Order Updates", "Receive updates about purchase order progress."], ["suppliers", "Supplier Updates", "Stay informed about supplier availability changes."]].map(([key, title, text]) => <ToggleRow key={key} title={title} text={text} enabled={notifications[key]} onToggle={() => toggleNotification(key)} />)}</div></SettingsSection>
        <SettingsSection title="Application Preferences" description="Adjust how SupplySync presents your workspace."><div className="grid grid-cols-1 gap-5 sm:grid-cols-2"><Field label="Currency"><select value={preferences.currency} onChange={(event) => setPreferences({ ...preferences, currency: event.target.value })} className="h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 text-sm text-slate-900 outline-none transition focus:border-blue-500 focus:bg-white focus:ring-4 focus:ring-blue-50"><option>INR</option><option>USD</option></select></Field><Field label="Dashboard Refresh"><select value={preferences.refresh} onChange={(event) => setPreferences({ ...preferences, refresh: event.target.value })} className="h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 text-sm text-slate-900 outline-none transition focus:border-blue-500 focus:bg-white focus:ring-4 focus:ring-blue-50"><option>Every 5 minutes</option><option>Every 15 minutes</option><option>Manual refresh</option></select></Field></div></SettingsSection>
        <SettingsSection title="Security" description="Authentication and account security are managed by Clerk."><div className="flex items-start gap-3 rounded-xl border border-blue-100 bg-blue-50 p-4"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-blue-100 font-bold text-blue-700">i</div><div><p className="text-sm font-semibold text-blue-900">Authentication managed by Clerk</p><p className="mt-1 text-sm leading-6 text-blue-800">Your sign-in, session and organization role are securely managed by Clerk. No authentication settings are changed here.</p></div></div></SettingsSection>
        <div className="flex flex-col items-center justify-end gap-3 border-t border-slate-200 pt-6 sm:flex-row"><p className={`text-sm font-medium ${saved ? "text-emerald-600" : "text-transparent"}`}>Changes saved locally</p><button type="button" onClick={() => setSaved(true)} className="w-full rounded-xl bg-blue-600 px-6 py-3 text-sm font-semibold text-white shadow-lg shadow-blue-600/20 transition hover:bg-blue-700 sm:w-auto">Save Changes</button></div>
      </div>
    </main>
  </div>;
}

function SettingsSection({ title, description, children }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 className="text-xl font-bold tracking-tight text-slate-900">{title}</h2><p className="mt-1 text-sm text-slate-500">{description}</p><div className="mt-6">{children}</div></section>; }
function Field({ label, children }) { return <label className="block"><span className="mb-2 block text-sm font-semibold text-slate-700">{label}</span>{children}</label>; }
function ToggleRow({ title, text, enabled, onToggle }) { return <div className="flex items-center justify-between gap-4 py-4 first:pt-0 last:pb-0"><div><p className="text-sm font-semibold text-slate-800">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{text}</p></div><button type="button" role="switch" aria-checked={enabled} onClick={onToggle} className={`relative h-6 w-11 shrink-0 rounded-full transition ${enabled ? "bg-blue-600" : "bg-slate-200"}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow-sm transition ${enabled ? "left-6" : "left-1"}`} /></button></div>; }

export default AccountSettingsPage;
